#!/bin/bash
usage(){
echo ""
echo "INVALID FORMAT"
echo ""
1>&2;
exit;
}

while getopts ":c:w:e:" o; do
	case "${o}" in
		c)
			c=${OPTARG}
			;;
		w)
			w=${OPTARG}
			;;
		e)
			e=${OPTARG}
			;;
		*)
			usage
			;;
	esac
done
shift $((OPTIND-1))

if [ -z "${c}" ] || [ -z "${w}" ] || [ -z "${e}" ]; then
	usage
fi

echo "c=${c}"
echo "w=${w}"
echo "e=${e}"
