#!/bin/bash
usage(){
echo ""
echo "Usage: $0 [-c] [-w] [-e]"
echo ""
echo "Options:"
echo "	-c percentage		Indicate the critical threshold percentage (Must"
echo "				be greater than the warning threshold)"
echo "	-w percentage		Indicate the warning threshold percentage"
echo "	-e email_address	Indicate the email address to send the report"
echo ""
1>&2;
exit;
}

while getopts ":c:w:e:" o; do
	case "${o}" in
		c)
			c=${OPTARG}
			;;
		w)
			w=${OPTARG}
			;;
		e)
			e=${OPTARG}
			;;
		*)
			usage
			;;
	esac
done
shift $((OPTIND-1))

if [ -z "${c}" ] || [ -z "${w}" ] || [ -z "${e}" ] || (( $c <= $w )) ||
	(( $c < 0 || $c > 100 )) || (( $w < 0 || $w > 100 )); then
	usage
fi

echo "c=${c}"
echo "w=${w}"
echo "e=${e}"
